version: '3.8'

services:
  chat-backend-dev:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: chat-backend-dev
    ports:
      - "8080:8080"
    volumes:
      # 소스 코드 마운트 (핫 리로드)
      - ./back/src:/app/src
      # 데이터베이스 파일
      - ./back/data:/app/data
      # 업로드 파일
      - ./back/uploads:/app/uploads
      # Gradle 캐시 (빌드 속도 향상)
      - gradle-cache:/root/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GRADLE_USER_HOME=/root/.gradle
    restart: unless-stopped
    
volumes:
  gradle-cache:
    driver: local